<?php
// XXX: The rsyslogd should be configurated to write the logs generated by
// openbts to /var/log/openbts.log, /var/log/openbts-cmd.log and
// /var/log/openbts-cmd-msg.log:
//
//   $FileCreateMode 0644
//   $umask 0000
//   if $programname == 'openbts' then /var/log/openbts.log
//   if $programname == 'openbts' and $msg contains 'CMD_' then /var/log/openbts-cmd.log
//   if $programname == 'openbts' and $msg contains 'CMD_Message' then /var/log/openbts-cmd-msg.log
//
define('CMD_MSG_LOG_PATH', "/var/log/openbts-cmd-msg.log");
define('CMD_LOG_PATH', "/var/log/openbts-cmd.log");

// XXX: The HTTP server must can execute any command as root.
// file: /etc/sudoers:
//   apache    ALL=(ALL) NOPASSWD:ALL
define('SERVICE_CONTROL_SCRIPT', "sudo /root/openbts/apps/run.sh");

// XXX: The directory saving the database file and the database itself must be
// writable by the HTTP server.
//   chmod 777 /etc/OpenBTS
//   chmod 777 /etc/OpenBTS/OpenBTS.db
define('DSN', "sqlite:/etc/OpenBTS/OpenBTS.db");

// XXX: The directory can be used to saving the data by apache. It should be
// writable by apache.
//   chmod -R 777 /var/www/html/data
define('DATA_DIR', "/var/www/html/data");
define('SMS_CSV_PATH', DATA_DIR . '/sms.csv');

// XXX: fgetcsv() needs the correct locale.
setlocale(LC_ALL, "zh_CN.UTF-8");

function no_cache()
{
  header('Cache-Control: no-cache, no-store, must-revalidate'); // HTTP 1.1.
  header('Pragma: no-cache'); // HTTP 1.0.
  header('Expires: 0'); // Proxies.
}

function collect_cmd($limit)
{
  $fp = fopen(CMD_LOG_PATH, "r");
  $res = array();
  if ($fp) {
    while (($line = fgets($fp)) !== false) {
      if (preg_match('/^(.{15}).*(CMD_.*)$/', $line, $matches)) {
        array_shift($matches);
        if (count($res) >= $limit)
          array_shift($res);
        $res[] = $matches;
      }
    }
    fclose($fp);
  }
  return array_reverse($res);
}

function collect_cmd_msg($limit, $start = null)
{
  $limit = $limit;
  if ($start !== null)
    $limit += $start;
  $res = array();
  $fp = fopen(CMD_MSG_LOG_PATH, 'r');
  if ($fp) {
    while (($line = fgets($fp)) !== false) {
      if (preg_match('/^(.{15}).*MobilityManagement.cpp:187:sendWelcomeMessage: CMD_Message From (\S+) to (\S+) Msg (.*)$/', $line, $matches)) {
        array_shift($matches);
        if (count($res) >= $limit)
          array_shift($res);
        $res[] = $matches;
      }
    }
    fclose($fp);
  }
  if ($start !== null) {
    if (count($res) < $start)
      return array();
    $limit = count($res) - $start;
    $rev = array();
    for ($i = 0; $i < $limit; $i++)
      array_unshift($rev, array_shift($res));
    return $rev;
  } else {
    return array_reverse($res);
  }
}

function echo_html($var)
{
  echo htmlspecialchars($var);
}

function show_settings($settings)
{
  no_cache();
?>
<div id="settings">
  <table>
    <tr>
      <th colspan="2">运营商</th>
      <td colspan="2">
<?php
  $value_to_text = array(
    "00" => "00 中国移动",
    "01" => "01 中国联通",
    "02" => "02 中国移动",
    "06" => "06 中国联通",
    "07" => "07 中国移动",
    "10" => "10 其他",
  );
?>
        <select name="GSM_Identity_MNC">
<?php
  foreach ($value_to_text as $v => $t) {
    if ($settings['GSM_Identity_MNC'] == $v)
      $selected = ' selected="selected"';
    else
      $selected = '';
?>
          <option value="<?php echo_html($v); ?>"<?php echo $selected; ?>><?php echo_html($t); ?></option>
<?php
  }
?>
        </select>
      </td>
    </tr>
    <tr>
      <th colspan="2">频点</th>
      <td colspan="2"><input type="text" name="GSM_Radio_C0" value="<?php echo_html($settings['GSM_Radio_C0']); ?>"><!-- [1, 124] --></td>
    </tr>
    <tr>
      <th colspan="2">发射功率</th>
      <td colspan="2"><input type="text" name="GSM_Radio_PowerManager_MaxAttenDB" value="<?php echo_html($settings['GSM_Radio_PowerManager_MaxAttenDB']); ?>"></td>
    </tr>
    <tr>
      <th colspan="2">多发条数</th>
      <td colspan="2">
        <select name="Control_LUR_MessageTotal">
<?php
  foreach (array(1, 2, 3) as $v) {
    $selected = '';
    if ($settings['Control_LUR_MessageTotal'] == $v)
      $selected = ' selected="selected"';
    echo '<option value="' . $v . '"' . $selected . '>' . $v . '</option>' . "\n";
  }
?>
        </select>
      </td>
<?php
  $items = array(
    array('一', ''),
    array('二', '1'),
    array('三', '2'),
  );
  foreach ($items as $item) {
?>
    <tr>
      <th rowspan="2">第<?php echo $item[0]; ?>条短信</th><th>内容</th>
      <td><textarea rows="4" cols="35" readonly="readonly" name="Control_LUR_OpenRegistration_Message<?php echo  $item[1];?>" onclick="open_dialog('<?php echo $item[1]; ?>');"><?php echo_html($settings['Control_LUR_OpenRegistration_Message' . $item[1]]);?></textarea></td>
      <td rowspan="2"><button onclick="open_dialog('<?php echo $item[1]; ?>');">选择</button></td>
    </tr>
    <tr>
      <th>主叫</th>
      <td><input type="text" name="Control_LUR_OpenRegistration_ShortCode<?php echo $item[1]; ?>" value="<?php echo_html($settings['Control_LUR_OpenRegistration_ShortCode' . $item[1]]); ?>" readonly="readonly" onclick="open_dialog('<?php echo $item[1]; ?>');"></td>
    </tr>
<?php
  }
?>
    <tr>
      <td colspan="4" style="text-align: right">
        <button onclick="submit_settings();">提交</button>
      </td>
    </tr>
  </table>
  <input type="hidden" name="submit" value="submit">
</div>
<?php
}

function show_operations()
{
  no_cache();
?>
<div id="operations">
<?php
  exec(SERVICE_CONTROL_SCRIPT . ' status', $output, $return_var);
  if ($return_var == 0 && trim($output[0]) == 'running') {
?>
  <button onclick="service('stop');">停止服务</button>
<?php
  } else {
?>
  <button onclick="service('start');">开始服务</button>
<?php
}
?>
  <button onclick="clean('log');">清空监控</button>
  <button onclick="clean('imsi');">清空IMSI</button>
  <br>
  发送监控:
  <br>
  <textarea style="width:100%; height:500px" readonly="readonly">
<?php
  $logs = collect_cmd(100);
  foreach ($logs as $log)
    echo_html(implode(" ", $log) . "\n");
?>
  </textarea>
</div>
<?php
}

function show_logs($page)
{
  $items_per_page = 20;
  $start = null;
  if ($page !== null)
    $start = $page * $items_per_page;
  $logs = collect_cmd_msg($items_per_page, $start);
  no_cache();
?>
<div id="logs">
  <table>
    <tr>
      <th>时间</th>
      <th>短信主叫</th>
      <th>短信被叫</th>
      <th>短信内容</th>
    </tr>
<?php
  foreach ($logs as $log) {
?>
    <tr>
      <td><?php echo_html($log[0]); ?></td>
      <td><?php echo_html($log[1]); ?></td>
      <td><?php echo_html($log[2]); ?></td>
      <td><?php echo_html($log[3]); ?></td>
    </tr>
<?php
  }
?>
  </table>
<?php
  if ($page !== null && intval($page) !== 0)
    echo "<button onclick=\"logs($page - 1);\">新</button>&nbsp;";
  echo "第";
  if ($page === null)
    $page = 0;
  echo $page + 1;
  echo "页&nbsp;";
  if (count($logs) >= $items_per_page)
    echo "<button onclick=\"logs($page + 1);\">旧</button>";
?>
</div>
<?php
}

function stat_cmd_msg()
{
  $stat = array();
  $fp = fopen(CMD_MSG_LOG_PATH, 'r');
  if ($fp) {
    while (($line = fgets($fp)) !== false) {
      if (preg_match('/.*MobilityManagement.cpp:187:sendWelcomeMessage: CMD_Message From \S+ to \S+ Msg (.*)$/', $line, $matches)) {
        if (isset($stat[$matches[1]]))
          $stat[$matches[1]]++;
        else
          $stat[$matches[1]] = 1;
      }
    }
    fclose($fp);
  }
  return $stat;
}

function show_statistics()
{
  $stats = stat_cmd_msg();
  no_cache();
?>
<div id="statistics">
  <table>
    <tr>
      <th>短信内容</th>
      <th>次数</th>
    </tr>
<?php
  foreach ($stats as $sms => $n) {
?>
    <tr>
      <td><?php echo_html($sms); ?></td>
      <td><?php echo $n; ?></td>
    </tr>
<?php
  }
?>
  </table>
</div>
<?php
}

function show_sms()
{
  no_cache();
?>
<div id="sms">
  <table>
    <tr>
      <td rowspan="2"><button onclick="add_sms();">添加</button></td>
      <th colspan="2">短信</th>
    </tr>
    <tr class="head">
      <th>内容</th>
      <th>主叫</th>
    </tr>
<?php
  $fp = fopen(SMS_CSV_PATH, 'r');
  if ($fp) {
    while (($row = fgetcsv($fp)) !== false) {
      $n = count($row);
      if ($n == 0)
        continue;
?>
    <tr class="content">
      <td><button onclick="delete_sms(this);">删除</button></td>
      <td><textarea rows="4" cols="35"><?php echo_html($row[0]); ?></textarea></td>
      <td><input type="text" value="<?php echo_html($row[1]); ?>"></td>
    </tr>
<?php
    }
    fclose($fp);
  }
?>
    <tr>
      <td colspan="3" style="text-align: right"><button onclick="submit_sms();">提交</button></td>
    </tr>
  </table>
</div>
<?php
}

function show_dialog()
{
  no_cache();
?>
<table style="width: 100%">
  <tr><th>内容</th><th>主叫</th></tr>
<?php
  $fp = fopen(SMS_CSV_PATH, "r");
  if ($fp) {
    while (($row = fgetcsv($fp)) !== false) {
      if (count($row) == 0)
        continue;
?>
  <tr onclick="highlight_row(this);"><td><pre><?php echo_html($row[0]); ?></pre></td><td><pre><?php echo_html($row[1]); ?></pre></td></tr>
<?php
    }
    fclose($fp);
  }
?>
</table>
<?php
}

$KEYS = array(
  "Control_LUR_OpenRegistration_Message",
  "Control_LUR_OpenRegistration_ShortCode",
  "Control_LUR_OpenRegistration_Message1",
  "Control_LUR_OpenRegistration_ShortCode1",
  "Control_LUR_OpenRegistration_Message2",
  "Control_LUR_OpenRegistration_ShortCode2",
  "GSM_Identity_MNC",
  "GSM_Radio_PowerManager_MaxAttenDB",
  "Control_LUR_MessageTotal",
  "GSM_Radio_C0"
);
if (isset($_POST['submit'])) {
  $db = new PDO(DSN);
  // TODO: sanity check, strip
  $sth = $db->prepare("UPDATE CONFIG SET VALUESTRING = ? WHERE KEYSTRING = ?");
  foreach ($KEYS as $k) {
    if (!$sth->execute(array($_POST[$k], str_replace("_", ".", $k)))) {
      exit("Failed to update " . str_replace("_", ".", $k));
    }
  }
  $db = null;
  no_cache();
  echo "success";
  exit;
} elseif (isset($_GET['submit']) && $_GET['submit'] == 'sms') {
  $json_str = file_get_contents('php://input');
  $sms = json_decode($json_str);
  $fp = fopen(SMS_CSV_PATH, "w");
  if ($fp) {
    foreach ($sms as $m)
      fputcsv($fp, $m);
    fclose($fp);
  }
  no_cache();
  echo "success";
  exit;
} elseif (isset($_GET['target'])) {
  if ($_GET['target'] == "settings") {
    $db = new PDO(DSN);
    $settings = array();
    foreach ($db->query('SELECT * FROM CONFIG') as $row) {
      if (in_array(str_replace(".", "_", $row['KEYSTRING']), $KEYS))
        $settings[str_replace(".", "_", $row['KEYSTRING'])] = $row['VALUESTRING'];
    }
    show_settings($settings);
  } elseif ($_GET['target'] == "operations") {
    show_operations();
  } elseif ($_GET['target'] == "logs") {
    show_logs(isset($_GET['page']) ? $_GET['page'] : null);
  } elseif ($_GET['target'] == 'statistics') {
    show_statistics();
  } elseif ($_GET['target'] == 'sms') {
    show_sms();
  } elseif ($_GET['target'] == 'dialog') {
    show_dialog();
  }
  $db = null;
  exit;
} elseif (isset($_GET['service'])) {
  if ($_GET['service'] == 'start' || $_GET['service'] == 'stop') {
    exec(SERVICE_CONTROL_SCRIPT . " " . $_GET['service'], $output, $return_var);
    if ($_GET['service'] == 'start')
      $msg = "开始服务";
    else
      $msg = "停止服务";
    no_cache();
    if ($return_var == 0) {
      echo "成功" . $msg;
    } else {
      echo $msg. "失败:";
      foreach ($output as $line)
        echo_html($line);
    }
  } else {
    echo "参数错误";
  }
  exit;
} elseif (isset($_GET['clean'])) {
  no_cache();
  if ($_GET['clean'] == 'log') {
    exec("sudo rm -f " . CMD_LOG_PATH);
    exec("sudo /etc/init.d/rsyslog restart");
  } elseif ($_GET['clean'] == 'imsi') {
    exec("sudo rm -f /var/run/OpenBTSTMSITable.db");
  } else {
    echo "参数错误";
  }
  exit;
}
no_cache();
?>
<!DOCTYPE HTML>
<html>
  <head>
    <meta charset="UTF-8">
    <title>BTS Administration</title>
    <link rel="stylesheet" type="text/css" href="css/jquery-ui.css">
    <style>
input, textarea, select {
  box-sizing: border-box;
  -ms-box-sizing: border-box;
  -moz-box-sizing: border-box;
  -webkit-box-sizing: border-box;
}

table {
  border-collapse: collapse;
  border-style: outset;
  border-width: 1px;
}

select {
  width: 100%;
}

th {
  border-width: 1px;
  border-style: outset;
  border-color: silver;
  background-color: #4297d7;
  color: white;
}

td {
  border-width: 1px;
  border-style: outset;
}

input[type=text] {
  width: 100%;
}

.highlight {
  background-color: #00ccff;
}

[readonly=readonly] {
  background-color: white;
}
    </style>
    <script src="js/jquery-1.10.2.js"></script>
    <script src="js/jquery-ui.js"></script>
    <script src="js/json2.js"></script>
    <script>
var refresh_operations_timer = undefined;
var sms_id = '';
$(function() {
  $('#tabs').tabs({
    beforeLoad: (function (event, ui) {
      ui.ajaxSettings.cache = false;
      if (refresh_operations_timer != undefined) {
        clearTimeout(refresh_operations_timer);
        refresh_operations_timer = undefined;
      }
    }),
    load: (function (event, ui) {
      $("#dialog").dialog("close");
      if (ui.tab.text() == '发送操作') {
        refresh_operations_timer = setTimeout(refresh_operations, 2000);
      }
      $('button').button();
    })
  });
  $("#dialog").dialog({
    autoOpen: false,
    buttons: [
      {
        text: "确定",
        click: function () {
          var vals = new Array();
          $(this).find("td.highlight pre").each(function (i, o) {
            vals.push($(o).text());
          });
          $("#settings textarea[name=Control_LUR_OpenRegistration_Message" + sms_id + ']').val(vals[0]);
          $("#settings input[name=Control_LUR_OpenRegistration_ShortCode" + sms_id + ']').val(vals[1]);
          $(this).dialog("close");
        }
      }
    ],
    height: 300,
    width: 400
  });
});

function service(op)
{
  $.ajax({
    url: '<?php echo $_SERVER['SCRIPT_NAME']; ?>' + '?service=' + op,
    cache: false
  }).done(function(text) {
    //alert(text);
  });
}

function clean(what)
{
  if (what == 'imsi') {
    if (!confirm("是否清空IMSI?")) {
      return;
    }
  }
  $.ajax({
    url: '<?php echo $_SERVER['SCRIPT_NAME']; ?>' + '?clean=' + what,
    cache: false
  }).done(function (text) {
    //alert(text);
  });
}

function logs(page)
{
  $.ajax({
    url: '<?php echo $_SERVER['SCRIPT_NAME']; ?>' + '?target=logs&page=' + page,
    cache: false
  }).done(function (html) {
    $('#logs').replaceWith(html);
    $('button').button();
  });
}

function refresh_operations()
{
  $.ajax({
    url: '<?php echo $_SERVER['SCRIPT_NAME']; ?>' + '?target=operations',
    cache: false
  }).done(function (html) {
    $('#operations').replaceWith(html);
    $('button').button();
  });
  refresh_operations_timer = setTimeout(refresh_operations, 2000);
}

function submit_settings()
{
  $.ajax({
    url: '<?php echo $_SERVER['SCRIPT_NAME']; ?>',
    cache: false,
    type: 'POST',
    data: $('#settings').find('input, textarea, select').serialize()
  }).done(function (text) {
    if (text == 'success') {
      alert("系统设置提交成功");
      $.ajax({
        url: '<?php echo $_SERVER['SCRIPT_NAME']; ?>' + '?target=settings',
        cache: false
      }).done(function (html) {
        $('#settings').replaceWith(html);
        $('button').button();
      });
    }
    // TODO: error
  });
}

function add_sms()
{
  $('#sms tr.head').after('<tr class="content">' +
      '<td><button onclick="delete_sms(this);">删除</button></td>' +
      '<td><textarea rows="4" cols="35"></textarea></td>' +
      '<td><input type="text" value=""></td>' +
      '</tr>');
  $('#sms textarea:first').focus();
  $('button').button();
}

function delete_sms(obj)
{
  $(obj).parent().parent().remove();
}

function submit_sms()
{
  var arr = new Array();
  $('#sms tr.content').each(function (i, tr) {
      arr.push([$(tr).find("textarea").val(), $(tr).find("input[type=text]").val()]);
  });
  $.ajax({
    url: '<?php echo $_SERVER['SCRIPT_NAME']; ?>' + '?submit=sms',
    cache: false,
    type: 'POST',
    contentType: 'application/json',
    data: JSON.stringify(arr)
  }).done(function (text) {
    if (text == 'success') {
      alert('短信提交成功');
      $.ajax({
        url: '<?php echo $_SERVER['SCRIPT_NAME']; ?>' + '?target=sms',
        cache: false
      }).done(function (html) {
        $('#sms').replaceWith(html);
        $('button').button();
      });
    }
    // TODO: error
  });
}

function open_dialog(id)
{
  sms_id = id;
  $.ajax({
    url: '<?php echo $_SERVER['SCRIPT_NAME']; ?>' + '?target=dialog',
    cache: false
  }).done(function (html) {
    $('#dialog').html(html);
    $("#dialog").dialog("open");
  });
}

function highlight_row(obj)
{
  $("#dialog td").removeClass("highlight");
  $(obj).find("td").addClass("highlight");
}
    </script>
  </head>
  <body>
    <div id="tabs">
      <ul>
        <li><a href="<?php echo $_SERVER['SCRIPT_NAME'] . "?target=operations"; ?>"><span>发送操作</span></a></li>
        <li><a href="<?php echo $_SERVER['SCRIPT_NAME'] . "?target=logs"; ?>"><span>发送日志</span></a></li>
        <li><a href="<?php echo $_SERVER['SCRIPT_NAME'] . "?target=statistics"; ?>"><span>业务统计</span></a></li>
        <li><a href="<?php echo $_SERVER['SCRIPT_NAME'] . "?target=settings"; ?>"><span>系统设置</span></a></li>
        <li><a href="<?php echo $_SERVER['SCRIPT_NAME'] . "?target=sms"; ?>"><span>短信编辑</span></a></li>
      </ul>
    </div>
    <div id="dialog" title="选择短信"></div>
  </body>
</html>
